### ISSUE TITLE
Unexpected crash when generating *.d.ts files for modules and 'sequelize'

### ISSUE THREAD

**Issue by pklochkov** [Microsoft/dts-gen#27]
Following error occurred when generating *.d.ts files for module 'sequelize'

C:\Users\pavel\Desktop\node development\card-processer>dts-gen -m sequelize
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:109
        throw e;
        ^

TypeError: Cannot read property 'getConnectorManager' of undefined
    at Sequelize.get (C:\Users\pavel\Desktop\node development\card-processer\node_modules\sequelize\lib\sequelize.js:315:35)
    at C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:272:143
    at Array.map (native)
    at getClassPrototypeMembers (C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:272:75)
    at getResult (C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:138:17)
    at getTopLevelDeclarations (C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:126:15)
    at Object.generateModuleDeclarationFile (C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:49:17)
    at Object.<anonymous> (C:\Users\pavel\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:54:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by mhegazy** [comment]
I think this should be addressed by https://github.com/Microsoft/dts-gen/pull/26. @RyanCavanaugh can we publish a new version?

**Comment by RyanCavanaugh** [comment]
Published 0.4.20. @pklochkov give it a try?

**Comment by crystalfp** [comment]
With 0.5.7 the problem persists. Tried with module `rdflib`.
